### PR TITLE
Merge and update benchmarks

### PR DESCRIPTION
**Pull request by cartermp**
Splits things into separate benchmarks.

I couldn't get the actual stuff you've built to run on my mac, but I could at least set things up so that there's baselines and memory analysis for each group during an All-hands 😄 

``` ini

BenchmarkDotNet=v0.11.5, OS=macOS Mojave 10.14.4 (18E226) [Darwin 18.5.0]
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview4-011223
  [Host]     : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT DEBUG
  DefaultJob : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT


```
|                 Method |     Mean |    Error |   StdDev | Ratio | RatioSD |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------- |---------:|---------:|---------:|------:|--------:|----------:|------:|------:|----------:|
| AsyncBinds_CSharpAsync | 170.9 ms | 3.381 ms | 7.493 ms |  1.00 |    0.00 | 5333.3333 |     - |     - | 2988925 B |
|        AsyncBinds_Task |       NA |       NA |       NA |     ? |       ? |         - |     - |     - |         - |
| AsyncBinds_TaskBuilder | 160.4 ms | 1.805 ms | 1.688 ms |  0.92 |    0.04 | 5250.0000 |     - |     - | 4800224 B |

Benchmarks with issues:
  AsyncBindsBenchmark.AsyncBinds_Task: DefaultJob

|                    Method |     Mean |     Error |    StdDev | Ratio | RatioSD |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |---------:|----------:|----------:|------:|--------:|----------:|------:|------:|----------:|
| ManyWriteFile_CSharpAsync | 26.43 ms | 0.5238 ms | 0.5379 ms |  1.00 |    0.00 |  625.0000 |     - |     - |    1904 B |
|        ManyWriteFile_Task |       NA |        NA |        NA |     ? |       ? |         - |     - |     - |         - |
| ManyWriteFile_TaskBuilder | 28.45 ms | 0.5682 ms | 0.9493 ms |  1.08 |    0.05 | 1687.5000 |     - |     - |    2185 B |
| ManyWriteFile_FSharpAsync | 44.78 ms | 1.0407 ms | 3.0522 ms |  1.80 |    0.11 | 2636.3636 |     - |     - |    3944 B |

Benchmarks with issues:
  ManyFileWriteBenchmark.ManyWriteFile_Task: DefaultJob

|                     Method |        Mean |     Error |    StdDev |      Median | Ratio | RatioSD |        Gen 0 | Gen 1 | Gen 2 |    Allocated |
|--------------------------- |------------:|----------:|----------:|------------:|------:|--------:|-------------:|------:|------:|-------------:|
| SingleSyncTask_CSharpAsync |    74.79 ms |  1.492 ms |  3.797 ms |    72.72 ms |  1.00 |    0.00 |            - |     - |     - |            - |
|        SingleSyncTask_Task |          NA |        NA |        NA |          NA |     ? |       ? |            - |     - |     - |            - |
| SingleSyncTask_TaskBuilder |   132.64 ms |  2.177 ms |  1.930 ms |   132.79 ms |  1.79 |    0.08 |  190500.0000 |     - |     - |  600000000 B |
| SingleSyncTask_FSharpAsync | 1,480.18 ms | 13.569 ms | 12.693 ms | 1,478.31 ms | 20.10 |    1.04 | 1220000.0000 |     - |     - | 3840000000 B |

Benchmarks with issues:
  SingleTaskBenchmark.SingleSyncTask_Task: DefaultJob

|                Method |       Mean |     Error |     StdDev | Ratio | RatioSD |       Gen 0 | Gen 1 | Gen 2 |    Allocated |
|---------------------- |-----------:|----------:|-----------:|------:|--------:|------------:|------:|------:|-------------:|
| SyncBinds_CSharpAsync |   111.5 ms |  2.204 ms |   3.860 ms |  1.00 |    0.00 | 251600.0000 |     - |     - |  792000000 B |
|        SyncBinds_Task |         NA |        NA |         NA |     ? |       ? |           - |     - |     - |            - |
| SyncBinds_TaskBuilder |   179.0 ms |  2.367 ms |   2.214 ms |  1.57 |    0.07 | 384000.0000 |     - |     - | 1208000000 B |
| SyncBinds_FSharpAsync | 1,234.2 ms | 35.586 ms | 101.529 ms | 10.94 |    1.07 | 895000.0000 |     - |     - | 2816000000 B |

Benchmarks with issues:
  SyncBindsBenchmark.SyncBinds_Task: DefaultJob

### CODE REVIEW

**Comment by dsyme** [comment]
Hmmm wonder why all the conflicts?

**Comment by cartermp** [comment]
Did have 'em when I submitted the PR...or at least that's what I thought.

**Comment by cartermp** [comment]
If it's easier to just copy-paste stuff into your branch then I'm 100% fine with that. My main goals here were to:

* Also have memory usage analysis
* Establish a baseline so it's easier to compare
* Split different experiments into different benchmarks for information presentation

**Comment by dsyme** [comment]
Thanks, merged manually

**Pull request closed without merging**
